workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "sit" || $CI_COMMIT_BRANCH == "uat" || $CI_COMMIT_BRANCH == "prod"'
stages:
  - "trigger_pipeline"
trigger_pipeline:
  stage: trigger_pipeline
  trigger:
    include:
      -  project: '$URL'
         ref: main
         file: '$FILE'
