import {getServerSession} from "next-auth";
import {authOption} from "@/app/lib/session/auth";
import {redirect} from "next/navigation";
import LoginForm from "@/app/components/layout/LoginForm";

export const metadata = {
    title: 'Redo | Log In',
    description: 'Generated by Next.js',
}
const Login = async () => {

    const session = await getServerSession(authOption);

    if (session){
        redirect("/sale/pos-invoice/pos-data")
    }

    return <LoginForm />
};

export default Login;
