import AuthLayout from "@/app/components/layout/AuthLayout";
import "@/app/styles/ks_bootstrap.css";
import "@/app/styles/redo.css";
import "@/app/styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthLayout>
          {children}
        </AuthLayout>
      </body>
    </html>
  )
}
